ALTER TABLE `users` CHANGE `online` `online` BOOLEAN NULL DEFAULT FALSE,
CHANGE `is_muted` `is_muted` BOOLEAN NULL DEFAULT FALSE,
CHANGE `block_newfriends` `block_newfriends` BOOLEAN NULL DEFAULT FALSE,
CHANGE `hide_online` `hide_online` BOOLEAN NULL DEFAULT FALSE,
CHANGE `hide_inroom` `hide_inroom` BOOLEAN NULL DEFAULT FALSE,
CHANGE `vip` `vip` BOOLEAN NULL DEFAULT TRUE,
CHANGE `focus_preference` `focus_preference` BOOLEAN NULL DEFAULT FALSE,
CHANGE `chat_preference` `chat_preference` BOOLEAN NULL DEFAULT FALSE,
CHANGE `pets_muted` `pets_muted` BOOLEAN NULL DEFAULT FALSE,
CHANGE `bots_muted` `bots_muted` BOOLEAN NULL DEFAULT FALSE,
CHANGE `advertising_report_blocked` `advertising_report_blocked` BOOLEAN NULL DEFAULT FALSE,
CHANGE `ignore_invites` `ignore_invites` BOOLEAN NULL DEFAULT FALSE,
CHANGE `allow_gifts` `allow_gifts` BOOLEAN NULL DEFAULT TRUE,
CHANGE `disable_forced_effects` `disable_forced_effects` BOOLEAN NOT NULL DEFAULT FALSE,
CHANGE `allow_mimic` `allow_mimic` BOOLEAN NOT NULL DEFAULT TRUE; 